FROM golang:alpine as builder

LABEL maintainer="thodorisanagnostopoulos0@gmail.com"

#Install Git
RUN apk update && apk add --no-cache git

# Set the current working directory inside the conatiner
WORKDIR /app

#Copy go mod and sum file
COPY go.mod go.sum ./

#Download all dependencies
RUN go mod download

#Copy the src from the current directory to the working dir inside the conatiner
COPY . . 

#Build the Go App
RUN CGO_ENABLED=0 GOOS=linux go build -a installsuffix cgo -o main .

#Start new stage from scratch
FROM alpine:latest
RUN apk --no-cache and ca-certificates

WORKDIR /root/

# Copy the Pre-built binary file from the previous stage. Observe we also copied the .env file
COPY --from=builder /app/main .
COPY --from=builder /app/.env .       

# Expose port 8000 to the outside world
EXPOSE 8000

#Command to run the executable
CMD ["./main"]